config/routes.rb
Rails.application.routes.draw do
  resources :clignes
  resources :blinks
  get 'home/index'
  root 'home#index'
  post 'clignes/:id/who' => 'clignes#who'

end

app/models/blink.rb
class Blink < ActiveRecord::Base
end

app/models/cligne.rb
class Cligne < ActiveRecord::Base
end

app/models/cligneur.rb
class Cligneur < ActiveRecord::Base
  belongs_to :cligne
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/blinks_controller.rb
class BlinksController < ApplicationController
  before_action :set_blink, only: [:show, :edit, :update, :destroy]

  # GET /blinks
  # GET /blinks.json
  def index
    @blinks = Blink.all
  end

  # GET /blinks/1
  # GET /blinks/1.json
  def show
  end

  # GET /blinks/new
  def new
    @blink = Blink.new
  end

  # GET /blinks/1/edit
  def edit
  end

  # POST /blinks
  # POST /blinks.json
  def create
    @blink = Blink.new(blink_params)

    respond_to do |format|
      if @blink.save
        format.html { redirect_to @blink, notice: 'Blink was successfully created.' }
        format.json { render :show, status: :created, location: @blink }
      else
        format.html { render :new }
        format.json { render json: @blink.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /blinks/1
  # PATCH/PUT /blinks/1.json
  def update
    respond_to do |format|
      if @blink.update(blink_params)
        format.html { redirect_to @blink, notice: 'Blink was successfully updated.' }
        format.json { render :show, status: :ok, location: @blink }
      else
        format.html { render :edit }
        format.json { render json: @blink.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /blinks/1
  # DELETE /blinks/1.json
  def destroy
    @blink.destroy
    respond_to do |format|
      format.html { redirect_to blinks_url, notice: 'Blink was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_blink
      @blink = Blink.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def blink_params
      params.require(:blink).permit(:status, :date)
    end
end

app/controllers/clignes_controller.rb
class ClignesController < ApplicationController
  before_action :set_cligne, only: [:show, :edit, :update, :destroy, :who]

# On saute une etape de securite si on appel BOOK en JSON
  skip_before_action :verify_authenticity_token, only: [:who, :create]

  # GET /clignes
  # GET /clignes.json
  def index
    @clignes = Cligne.all
  end

  # GET /clignes/1
  # GET /clignes/1.json
  def show
  end

  # GET /clignes/new
  def new
    @cligne = Cligne.new
  end

  # GET /clignes/1/edit
  def edit
  end

  # POST /clignes
  # POST /clignes.json
  def create
    @cligne = Cligne.new(cligne_params)

    respond_to do |format|
      if @cligne.save
        format.html { redirect_to @cligne, notice: 'Cligne was successfully created.' }
        format.json { render :show, status: :created, location: @cligne }
      else
        format.html { render :new }
        format.json { render json: @cligne.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /clignes/1
  # PATCH/PUT /clignes/1.json
  def update
    respond_to do |format|
      if @cligne.update(cligne_params)
        format.html { redirect_to @cligne, notice: 'Cligne was successfully updated.' }
        format.json { render :show, status: :ok, location: @cligne }
      else
        format.html { render :edit }
        format.json { render json: @cligne.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /clignes/1
  # DELETE /clignes/1.json
  def destroy
    @cligne.destroy
    respond_to do |format|
      format.html { redirect_to clignes_url, notice: 'Cligne was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

# POST /shows/1/book.json
  def who
    # On crée un nouvel objet booking à partir des paramètres reçus
    @cligner = Cligneur.new(cligneur_params)
    # On précise que cet object Booking dépend du show concerné
    @cligner.cligne = @cligne

    respond_to do |format|
      if @cligner.save
        format.json
      else
        format.json { render json: @cligner.errors, status: :unprocessable_entity }
      end
    end
  end


  private
    # Use callbacks to share common setup or constraints between actions.
    def set_cligne
      @cligne = Cligne.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def cligne_params
      params.require(:cligne).permit(:status, :date)
    end

    # On ajoute les paramètres qu'on va envoyer avec le booking
    def cligneur_params
      params.require(:cligneur).permit(:user_name)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/blinks_helper.rb
module BlinksHelper
end

app/helpers/clignes_helper.rb
module ClignesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/blinks/_form.html.erb
<%= form_for(@blink) do |f| %>
  <% if @blink.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@blink.errors.count, "error") %> prohibited this blink from being saved:</h2>

      <ul>
      <% @blink.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :status %><br>
    <%= f.text_field :status %>
  </div>
  <div class="field">
    <%= f.label :date %><br>
    <%= f.date_select :date %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/blinks/edit.html.erb
<h1>Editing Blink</h1>

<%= render 'form' %>

<%= link_to 'Show', @blink %> |
<%= link_to 'Back', blinks_path %>

app/views/blinks/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Blinks</h1>

<table>
  <thead>
    <tr>
      <th>Status</th>
      <th>Date</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @blinks.each do |blink| %>
      <tr>
        <td><%= blink.status %></td>
        <td><%= blink.date %></td>
        <td><%= link_to 'Show', blink %></td>
        <td><%= link_to 'Edit', edit_blink_path(blink) %></td>
        <td><%= link_to 'Destroy', blink, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Blink', new_blink_path %>

app/views/blinks/new.html.erb
<h1>New Blink</h1>

<%= render 'form' %>

<%= link_to 'Back', blinks_path %>

app/views/blinks/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Status:</strong>
  <%= @blink.status %>
</p>

<p>
  <strong>Data:</strong>
  <%= @blink.date %>
</p>

<%= link_to 'Edit', edit_blink_path(@blink) %> |
<%= link_to 'Back', blinks_path %>

app/views/clignes/_form.html.erb
<%= form_for(@cligne) do |f| %>
  <% if @cligne.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@cligne.errors.count, "error") %> prohibited this cligne from being saved:</h2>

      <ul>
      <% @cligne.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :status %><br>
    <%= f.text_field :status %>
  </div>
  <div class="field">
    <%= f.label :date %><br>
    <%= f.date_select :date %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/clignes/edit.html.erb
<h1>Editing Cligne</h1>

<%= render 'form' %>

<%= link_to 'Show', @cligne %> |
<%= link_to 'Back', clignes_path %>

app/views/clignes/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Clignes</h1>

<table>
  <thead>
    <tr>
      <th>Status</th>
      <th>Date</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @clignes.each do |cligne| %>
      <tr>
        <td><%= cligne.status %></td>
        <td><%= cligne.date %></td>
        <td><%= link_to 'Show', cligne %></td>
        <td><%= link_to 'Edit', edit_cligne_path(cligne) %></td>
        <td><%= link_to 'Destroy', cligne, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Cligne', new_cligne_path %>

app/views/clignes/new.html.erb
<h1>New Cligne</h1>

<%= render 'form' %>

<%= link_to 'Back', clignes_path %>

app/views/clignes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Status:</strong>
  <%= @cligne.status %>
</p>

<p>
  <strong>Date:</strong>
  <%= @cligne.date %>
</p>

<%= link_to 'Edit', edit_cligne_path(@cligne) %> |
<%= link_to 'Back', clignes_path %>

app/views/home/index.html.erb
<h1>Hello World!!</h1>
<p>Find me in app/views/home/index.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Tryagainrails</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>